source 'https://github.com/CocoaPods/Specs.git'
platform :ios,'9.0'

#post_install do |installer|
#  installer.pods_project.build_configurations.each do |config|
#    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
#  end
#end

use_frameworks!
target 'Code' do

    
pod 'JSONModel', '~> 1.1.2'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'AFNetworking', '~> 4.0.0'
pod 'SDWebImage', '~> 5.13.0'

#pod 'SDWebImage/GIF'
#pod 'SDWebImage/WebP'

pod 'Masonry'

pod 'UITableView+FDTemplateLayoutCell'
pod 'MJRefresh' ,'~> 3.1.15.7'
pod 'EAIntroView', '~> 2.10.0'
pod 'MRProgress'
pod 'IQKeyboardManager' , '~> 6.2.0'
pod 'MJExtension'
#pod 'CocoaLumberjack'
#pod 'PYSearch'
pod 'SDAutoLayout', '~> 2.2.0'
#pod 'UMengUShare/Social/WeChat'

pod 'UMShare/Social/QQ'
pod 'UMShare/Social/Sina'
pod 'UMShare/UI'
pod 'UMCCommonLog'
#//必须集成
pod 'UMCommon' #//由原来的UMCCommon变为UMCommon
pod 'UMDevice'
pod 'UMAPM'
#pod 'UMengAnalytics'  #pod 'UMengAnalytics-NO-IDFA'

    
pod 'DZNEmptyDataSet'

pod 'CYLTabBarController', '~>1.18.0' #修改tab阴影

#pod 'ZFNormalPlayer', '~> 2.1.5'
pod 'ASIHTTPRequest', '~> 1.8.2'
pod 'JSBadgeView','~> 1.4.1'#角标
#pod 'MLeaksFinder'
pod 'SVProgressHUD', '~> 2.1.2'

pod 'LUKeychainAccess', '~> 2.0.2'
pod 'SDCycleScrollView','~> 1.66'
pod 'WMPageController'  #修改该库 -- 添加菜单分隔线
pod 'MZTimerLabel', '~> 0.5.4'

pod 'TYAttributedLabel'
pod 'JPush', '3.3.6'
pod 'JCore', '2.4.0'
#pod 'JMLink'
pod 'WebViewJavascriptBridge', '~> 6.0.3'
pod 'YYText'
pod 'DTCoreText',   '~>1.6.21'
pod 'Bugly' , '~> 2.5.9'
pod 'TBScrollViewEmpty' #虎课自己内部的开发框架
pod 'YYWebImage' #虎课自己内部的开发框架

#ae动画
pod 'lottie-ios', '~> 2.5.3'
pod 'M80AttributedLabel', '~> 1.7.0'
pod 'Toast', '~> 4.0.0'
pod 'TZImagePickerController', '~> 3.0.9'

pod 'ZFPlayer', '~> 4.1.0'
pod 'ZFPlayer/ControlView', '~> 4.1.0'
pod 'ZFPlayer/AVPlayer', '~> 4.1.0'
pod 'ZFPlayer/ijkplayer', '~> 4.1.0'

#pod 'AliyunSlsObjc'
pod 'AliyunLogProducer', '~> 2.2.12'

pod 'MRDLNA'

pod 'IGListKit'
#pod 'ZXingObjC'


#pod 'PolyvCloudClassSDK', '0.12.1' , :subspecs => ['Core','Player'] # 具体版本号可使用当前正在使用的SDK版本号
#pod 'AgoraRtcEngine_iOS', '2.9.0.102' # 0.11.1 及以下版本云课堂SDK 请将此库改成 2.8.0
#pod 'PolyvAliHttpDNS','~> 1.6.7'
#pod 'PLVSocket', '~> 0.1.3'


pod 'FluentDarkModeKit', :git=>'https://github.com/lzylzy1991/FluentDarkModeKit.git'
pod 'PolyvCloudClassSDK', '0.12.1' # polyv 云课堂 SDK
pod 'ReactiveObjC','3.1.1'
pod 'Qiniu'
pod 'SuperPlayer','3.6.2'
pod 'TXLiteAVSDK_Player', :podspec => 'https://mediacloud-76607.gzc.vod.tencent-cloud.com/Podspec/TXCTbPlayer/10.6.11823/TXLiteAVSDK_Player.podspec'
end






#去除库警告
#inhibit_all_warnings!

# 更新框架-已加入框架不会再次更新
# pod install --verbose --no-repo-update

# pod update SDWebImage --verbose --no-repo-update
# pod update MBProgressHUD --verbose --no-repo-update


# pod update Bugly --verbose --no-repo-update

#Masonry
# pod update ZFPlayer --verbose --no-repo-update


# pod install MLeaksFinder --verbose --no-repo-update

#find ~/.cocoapods/repos/master -iname SDWebImage


# Pod 本地文件目录
#/Users/ivanli/Library/Caches/CocoaPods/Pods/Release/
#/Users/hanchuangkeji/Library/Caches/CocoaPods/Pods/Release/

#/Users/ivanli/Library/Caches/CocoaPods/Pods/Specs/Release/libwebp




#删除 search_index.json
#rm ~/Library/Caches/CocoaPods/search_index.json

# Pod 安装目录
#~/.cocoapods/repos


#SDWebImage/WebP 更新方法 替换 下面路径中的json  将google 源 换成 github
#/Users/ivan/.cocoapods/repos/master/Specs/1/9/2/libwebp
#https://chromium.googlesource.com/webm/libwebp
#https://github.com/webmproject/libwebp.git

# open /Users/yxma/.cocoapods/repos/cocoapods/Specs/1/9/2/libwebp

